### ISSUE TITLE
Add 'failover_peer' key to 'pool' directive in README.md file

### ISSUE THREAD

**Issue by kemeris2000** [bertvv/ansible-role-dhcp#59]

**Comment by aturbin-35** [comment]
Hello,

I want to react on this topic.
I'm facing an issue or maybe a misunderstanding.

ISC documentation says that when you wan to operate a subnet with the failover mechanism, you need to declare the failover peer in a pool section.
In this role, the readme say that it support failover statement.
But you can't actually declare the failover peer in a subnet (which seems to be mandatory at least for the subnet where the dhcp server IP belongs).

Maybe it's not mandatory but since the "dhcp -t" command indicate that the failover statement is missing, it seems like there is no other way to do.
In an other hand, there is no failover peer statement for the subnet block in your template.

The reference  from ISC (point 6) -> https://kb.isc.org/docs/aa-00502 

Could you please enlighten me on this point ? 

Thank you
